# Generated by Django 3.0.5 on 2020-04-12 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
