# Generated by Django 3.0.5 on 2020-04-13 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_roomuseranswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomuseranswers',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_question', to='questions.Question'),
        ),
        migrations.AlterField(
            model_name='roomuseranswers',
            name='first_to_answer_user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
