# Generated by Django 3.0.5 on 2020-04-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20200413_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomuseranswers',
            name='created',
        ),
    ]
