# Generated by Django 3.0.5 on 2020-04-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_remove_roomuseranswers_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomuseranswers',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
